version: '3.5'
services:
  maps:
    build:
      context: ../../
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.hom
    command: npm run start:prod
    networks:
      - backend
      
networks:
  backend:
    external:
      name: cartografia-network