version: '3.5'
services:
  dev:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    volumes: 
      - .:/var/www/gateway
    restart: always
    hostname: maps
    env_file:
      - .env
    networks:
      - backend
  maps:
    build: .
    restart: always
    hostname: maps
    env_file:
      - .env
    networks:
      - backend

  debug:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    volumes: 
      - .:/var/www/gateway
    ports: 
      - 9227:9227
    command: npm run start:debug
    hostname: maps
    env_file:
      - .env
    networks:
      - backend
      
networks:
  backend:
    external:
      name: cartografia-network